update - ci/cd pipeline

diff --git a/.github/workflows/ci-cd-pipeline.yaml b/.github/workflows/ci-cd-pipeline.yaml
--- a/.github/workflows/ci-cd-pipeline.yaml
+++ b/.github/workflows/ci-cd-pipeline.yaml
@@ -181,11 +181,13 @@ jobs:
           # Check if frontend service deployment succeeded
           if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -qE '^(open-telemetry-demo/src/frontend/|phase2/deployment/open-telemetry/6-webApplication/3-frontend/1-frontend-service/.*\.yaml$)'; then
             timeout 150 kubectl rollout status deployment/opentelemetry-demo-frontend --namespace otel-demo
+            DEPLOYMENT_EXIT_CODE=$?  # Capture the exit code of the timeout command
+
              # Check the exit status of the timeout command
-            if [ $? -eq 124 ]; then
+            if [ $DEPLOYMENT_EXIT_CODE -eq 124 ]; then
               echo "Deployment timed out. Rolling back to previous version..."
               kubectl rollout undo deployment/opentelemetry-demo-frontend --namespace otel-demo
-            elif [ $? -ne 0 ]; then
+            elif [ $DEPLOYMENT_EXIT_CODE -ne 0 ]; then
               echo "Deployment failed. Rolling back to previous version..."
               kubectl rollout undo deployment/opentelemetry-demo-frontend --namespace otel-demo
             else
