update - ci/cd

diff --git a/.github/workflows/testing.yaml b/.github/workflows/testing.yaml
--- a/.github/workflows/testing.yaml
+++ b/.github/workflows/testing.yaml
@@ -23,6 +23,19 @@ jobs:
       - name: check out code
         uses: actions/checkout@v4
 
+      - name: Load environment variables from .env file
+        run: |
+          cd ./open-telemetry-demo
+          if [ -f .env ]; then
+            # Filter out comments and empty lines, then add each variable to $GITHUB_ENV
+            grep -vE '^\s*#|^\s*$' .env | while read -r line; do
+              echo "$line" >> $GITHUB_ENV
+            done
+          else
+            echo ".env file not found!"
+            exit 1
+          fi
+
       - name: run tracetesting
         run: |
           cd ./open-telemetry-demo && make build && docker system prune -f && make run-tracetesting
