update

diff --git a/.github/workflows/testing.yaml b/.github/workflows/testing.yaml
--- a/.github/workflows/testing.yaml
+++ b/.github/workflows/testing.yaml
@@ -26,9 +26,14 @@ jobs:
       - name: Load environment variables from .env file
         run: |
           cd ./open-telemetry-demo
+          if [ ! -d "./open-telemetry-demo" ]; then
+            echo "Directory './open-telemetry-demo' not found!"
+            exit 1
+          fi
           if [ -f .env ]; then
             # Filter out comments and empty lines, then add each variable to $GITHUB_ENV
-            grep -vE '^\s*#|^\s*$' .env | while read -r line; do
+            echo "Reading .env file!"
+            grep -vE '^\s*#|^\s*$' .env | grep -E '^[^=]+=[^=]+$' | while read -r line; do
               echo "$line" >> $GITHUB_ENV
             done
           else
